### ISSUE TITLE
"Reclared import module 'ballerina/io'" error is always shown 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/plugin-vscode#156]
**Description:**
Please consider the following screen capture

![Screenshot from 2021-01-21 17-54-41](https://user-images.githubusercontent.com/19838787/105350996-f2a48600-5c11-11eb-94d0-c86f46eb9952.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by riyafa** [comment]
Noticed the same issue for mysql import, though the build completes successfully on the terminal

**Comment by prabushi** [comment]
@lasinicl and @riyafa could you please attach the full project when this error occurs?

**Comment by lasinicl** [comment]
> @lasinicl and @riyafa could you please attach the full project when this error occurs?

After working for some time, I'm no longer seeing this error.

**Comment by riyafa** [comment]
I restarted and the error goes away

**Comment by prabushi** [comment]
This could be related to https://github.com/ballerina-platform/ballerina-lang/issues/28069. Please attach the project if you see the mentioned error even after this fix.

**Comment by riyafa** [comment]
I frequently see errors that appeared once continuing to exist even once we have fixed the errors. The issue I think is with the errors not disappearing, but continuing to linger.

**Comment by lasinicl** [comment]
I'm still seeing this issue intermittently with the latest vscode plugin as well(2.0.0-alpha)

**Comment by prabushi** [comment]
As per @lasinicl, this is no longer reproducible with the latest alph1 distribution and its corresponding vsix. Hence, closing the issue.
